### ISSUE TITLE
Can't resolve 'simple-line-icons\css\simple-line-icons.css'

### ISSUE THREAD

**Issue by v1shva** [coreui/coreui-free-angular-admin-template#196]
I get following error at `npm start` or `npm run-script build` after cloning the repo.

> ERROR in multi ./node_modules/@coreui/icons/css/coreui-icons.css ./node_modules/flag-icon-css/css/flag-icon.css ./node_modules/font-awesome/css/font-awesome.css ./node_modules/simple-line-icons/css/simple-line-icons.css ./src/scss/style.scss Module not found: Error: Can't resolve 'C:\XXXXX\coreui-free-angular-admin-template\node_modules\simple-line-icons\css\simple-line-icons.css' in 'F:\Private\test\coreui-free-angular-admin-template'

**Comment by v1shva** [comment]
For now this can be fixed by updating the package.json `"simple-line-icons": "^2.4.1"` to `"simple-line-icons": "2.4.1"`

**Comment by xidedix** [comment]
@v1shva Thanks for the heads up!

There is a breaking change between `v2.4.x` and the latest `v2.5.x` of `simple-line-icons`

The path changed from `~simple-line-icons/css/simple-line-icons` to `~simple-line-icons/dist/styles/simple-line-icons`

As a quick fix you have two options: 
1. in `package.json` fix the version of `simple-line-icons` to `~2.4.1` instead of `^2.4.1`
or
2. in `angular.json`​ change 
- from: `"node_modules/simple-line-icons/css/simple-line-icons.css",`
- to: `"node_modules/simple-line-icons/dist/styles/simple-line-icons.css",`
