### ISSUE TITLE
Module '"@coreui/angular"' has no exported member 'AppBreadcrumbModule'

### ISSUE THREAD

**Issue by prabas88** [coreui/coreui-free-angular-admin-template#217]
After updating to 
 "@coreui/angular": "^4.0.0-alpha.8",
"@coreui/coreui-pro": "^4.1.0",

application cannot find the core modules like 

  AppAsideModule,
  AppBreadcrumbModule,
  AppHeaderModule,
  AppFooterModule,
  AppSidebarModule

Module '"@coreui/angular"' has no exported member 'AppBreadcrumbModule'

**Comment by xidedix** [comment]
@prabas88 
The migration to v4 doesn't work this way since there are some breaking changes.

Feel free to see the docs:
- https://coreui.io/angular/docs/4.0/components/breadcrumb
- https://coreui.io/angular/docs/4.0/components/header
- https://coreui.io/angular/docs/4.0/components/footer
- https://coreui.io/angular/docs/4.0/components/sidebar
